# .github/release-drafter.yml
# Maintains draft release with ALL commits and PRs

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Auto-bump version based on labels
version-resolver:
  major:
    labels:
      - breaking
      - semver:major
      - major
  minor:
    labels:
      - feature
      - enhancement
      - semver:minor
      - minor
  patch:
    labels:
      - fix
      - bug
      - bugfix
      - chore
      - maintenance
      - refactor
      - deps
      - dependencies
      - semver:patch
      - patch
  default: patch

# Categorize ALL changes (PRs and commits)
categories:
  - title: '🚨 Breaking Changes'
    labels:
      - breaking
      - semver:major
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
      - bugfix
  - title: '🧰 Maintenance'
    labels:
      - chore
      - maintenance
      - refactor
  - title: '📦 Dependencies'
    labels:
      - deps
      - dependencies
  - title: '🧪 Tests'
    labels:
      - test
      - tests
  - title: '📚 Documentation'
    labels:
      - docs
      - documentation
  - title: '🧱 CI/CD'
    labels:
      - ci
      - github-actions
      - workflow
  - title: '🔧 Configuration'
    labels:
      - config
      - build
      - packaging

# IMPORTANT: Don't exclude anything - include ALL changes
exclude-labels: []
exclude-contributors: []

# Include ALL commits, even without PRs
include-commits: true

# Per-change template with full context
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
no-changes-template: '- No changes in this release'

# Don't collapse - show everything
collapse-after: 999

# Auto-label PRs from commit messages (conventional commits)
autolabeler:
  - label: breaking
    title:
      - '/!:/'
      - '/breaking/i'
      - '/^[a-z]+(\(.+\))?!:/'
  - label: feature
    title:
      - '/^feat(\(.+\))?:/i'
  - label: bug
    title:
      - '/^fix(\(.+\))?:/i'
  - label: docs
    title:
      - '/^docs(\(.+\))?:/i'
  - label: chore
    title:
      - '/^chore(\(.+\))?:/i'
  - label: refactor
    title:
      - '/^refactor(\(.+\))?:/i'
  - label: test
    title:
      - '/^test(\(.+\))?:/i'
  - label: ci
    title:
      - '/^ci(\(.+\))?:/i'
  - label: dependencies
    title:
      - '/deps?/i'
      - '/bump/i'
      - '/^build(\(.+\))?:/i'

# Track all branches or specific branch
# branches:
#  - main

# Comprehensive template with ALL information
template: |
  ## What's Changed

  $CHANGES

  ## All Contributors

  Thank you to everyone who contributed to this release! 💜

  $CONTRIBUTORS

  ## Full Changelog

  **Full Diff**: $COMPARE_URL

  ---

  *This release was automatically generated from commits and pull requests merged since the last release.*
